### ISSUE TITLE
Episoden-Detailseiten Font

### ISSUE THREAD

**Issue by mabe-at** [aua-uff-code/aua-uff-co.de#5]
Die Detailseiten der Episoden werden mit "Serif"-Font angezeigt.
Ich habe jetzt auf die Schnelle nicht herausgefunden, was da fehlt bzw. nich eingebunden wird.

**Comment by haslinger** [comment]
Die Layouts waren gleich an einigen Stellen auseinandergelaufen. 
(Hatte vergessen, dass es da ein weiteres gibt.) Ist jetzt gefixt.
